# ================== 数据库字段名 -> 标准字段名映射 ==================
from config.config import DefaultSetting


DB_COLUMN_MAPS = {
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.PORTS_FILENAME]: {
        'id': 'PortID',
        'port_id': 'PortID',
        'port': 'Port',
        'name': 'Port',
        'whether_trans': 'WhetherTrans',
        'region': 'Region',
        'group': 'Group',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.ROUTES_FILENAME]: {
        'id': 'ShippingRouteID',
        'cycle_time': 'CycleTime',
        'num_round_trips': 'NumRoundTrips',
        'number_of_ports': 'NumberOfPorts',
        'number_of_calls': 'NumberOfCall',
        'ports_of_call': 'PortsOfCall',
        'port_call_sequence': 'PortCallSequence',
        'time': 'Time',
        'times': 'Time',
        'ports': 'Ports',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.VESSELS_FILENAME]: {
        'id': 'VesselID',
        'vessel_id': 'VesselID',
        'capacity': 'Capacity',
        'operating_cost': 'OperatingCost',
        'route_id': 'RouteID',
        'max_num': 'MaxNum',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.NODES_FILENAME]: {
        'id': 'ID',
        'node_id': 'ID',
        'route': 'Route',
        'call': 'Call',
        'port': 'Port',
        'round_trip': 'RoundTrip',
        'time': 'Time',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.TRAVELING_ARCS_FILENAME]: {
        'id': 'TravelingArcID',
        'traveling_arc_id': 'TravelingArcID',
        'route': 'Route',
        'round_trip': 'RoundTrip',
        'origin_node_id': 'OriginNodeID',
        'origin_call': 'OriginCall',
        'origin_port': 'OriginPort',
        'origin_time': 'OriginTime',
        'traveling_time': 'TravelingTime',
        'destination_node_id': 'DestinationNodeID',
        'destination_call': 'DestinationCall',
        'destination_port': 'DestinationPort',
        'destination_time': 'DestinationTime',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.TRANSSHIP_ARCS_FILENAME]: {
        'id': 'TransshipArcID',
        'transship_arc_id': 'TransshipArcID',
        'port': 'Port',
        'origin_node_id': 'OriginNodeID',
        'origin_time': 'OriginTime',
        'transship_time': 'TransshipTime',
        'destination_node_id': 'DestinationNodeID',
        'destination_time': 'DestinationTime',
        'from_route': 'FromRoute',
        'to_route': 'ToRoute',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.PATHS_FILENAME]: {
        'id': 'PathID',
        'container_path_id': 'ContainerPathID',
        'origin_port': 'OriginPort',
        'origin_time': 'OriginTime',
        'destination_port': 'DestinationPort',
        'destination_time': 'DestinationTime',
        'path_time': 'PathTime',
        'transship_port': 'TransshipPort',
        'transship_time': 'TransshipTime',
        'port_path_length': 'PortPathLength',
        'port_path': 'PortPath',
        'arcs_length': 'ArcsLength',
        'arcs_id': 'ArcsID',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.LADEN_PATHS_FILENAME]: {
        'request_id': 'RequestID',
        'origin_port': 'OriginPort',
        'origin_time': 'OriginTime',
        'destination_port': 'DestinationPort',
        'round_trip': 'RoundTrip',
        'earliest_set_up_time': 'EarliestSetUpTime',
        'arrival_time_to_destination': 'ArrivalTimeToDestination',
        'path_time': 'PathTime',
        'transship_port': 'TransshipPort',
        'transship_time': 'TransshipTime',
        'path_id': 'PathID',
        'port_path': 'PortPath',
        'arc_ids': 'ArcIDs',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.EMPTY_PATHS_FILENAME]: {
        'request_id': 'RequestID',
        'origin_port': 'OriginPort',
        'origin_time': 'OriginTime',
        'num_of_empty_path': 'NumOfEmptyPath',
        'path_ids': 'PathIDs',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.REQUESTS_FILENAME]: {
        'id': 'RequestID',
        'request_id': 'RequestID',
        'origin_port': 'OriginPort',
        'destination_port': 'DestinationPort',
        'w_i_earlist': 'EarliestPickupTime',
        'earliest_pickup_time': 'EarliestPickupTime',
        'latest_destination_time': 'LatestDestinationTime',
        'laden_paths': 'LadenPaths',
        'number_of_laden_path': 'NumberOfLadenPath',
        'empty_paths': 'EmptyPaths',
        'number_of_empty_path': 'NumberOfEmptyPath',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.DEMAND_RANGE_FILENAME]: {
        'origin_region': 'OriginRegion',
        'destination_region': 'DestinationRegion',
        'demand_lower_bound': 'DemandLowerBound',
        'demand_upper_bound': 'DemandUpperBound',
        'freight_lower_bound': 'FreightLowerBound',
        'freight_upper_bound': 'FreightUpperBound',
    },
    DefaultSetting.FILE_TABLE_MAP[DefaultSetting.VESSEL_PATHS_FILENAME]: {
        'id': 'VesselPathID',
        'vessel_path_id': 'VesselPathID',
        'vessel_route_id': 'ShippingRouteID',
        'route_id': 'ShippingRouteID',
        'route': 'ShippingRouteID',
        'number_of_arcs': 'NumberOfArcs',
        'arc_ids': 'ArcIDs',
        'arcs_id': 'ArcIDs',
        'origin_time': 'OriginTime',
        'destination_time': 'DestinationTime',
        'path_time': 'PathTime',
    },
    # 如有其他表，按上述格式补充
}

# ================== 本地文件名 <-> 数据库表名映射 ==================
FILE_TABLE_MAP = {
    'Ports.txt': 'ports',
    'Vessels.txt': 'ships',
    'ShippingRoutes.txt': 'routes',
    'Nodes.txt': 'nodes',
    'TransshipArcs.txt': 'transship_arcs',
    'TravelingArcs.txt': 'traveling_arcs',
    'Paths.txt': 'paths',
    'Requests.txt': 'requests',
    # 其他文件可按需补充
}